[theme]
primaryColor = "#286B79"
backgroundColor = "#F7F8F6"
secondaryBackgroundColor = "#EDF4F4"
textColor = "#263E49"
font = "sans-serif"

[server]
headless = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
